site_name: 'HCSM User Manual'
nav:
  - Home: gettingstartedhtmlversion.md
  - Overview: gettingstartedhtmlversion.md#Purpose
  - Purpose: 
  - Target audience: 
  - Scope of the solution: 
  - System requirements: 
  - Getting Started:
  - Features Overview: 
  - Scope of the solution: 
  
plugins:
  - techdocs-core
