site_name: 'HCSM User Manual'
nav:
  - Home: gettingstartedhtmlversion.md
  - Overview: index.md
  - Purpose: gettingstartedhtmlversion.md#purpose
  - Target audience: gettingstartedhtmlversion3.md
  - Scope of the solution: gettingstartedhtmlversion4.md
  - System requirements: gettingstartedhtmlversion5.md
  - Getting Started: gettingstartedhtmlversion6.md
  - Features Overview: gettingstartedhtmlversion7.md
  - Scope of the solution: gettingstartedhtmlversion8.md

plugins:
  - techdocs-core
