
site_name: 'HCSM User Manual'
nav:
  - Home: gettingstartedhtmlversion.md
  - Purpose: gettingstartedhtmlversion.md#purpose
  - Target audience: gettingstartedhtmlversion.md#target-audience
  - Scope of the solution: gettingstartedhtmlversion.md#scope-of-the-solution
  - System requirements: gettingstartedhtmlversion.md#system-requirements
  - Getting Started: gettingstartedhtmlversion.md#getting-started
  - Features Overview: gettingstartedhtmlversion.md#features-overview
      - User Authentication: gettingstartedhtmlversion.md#user-uthentication
      - Provider Account: gettingstartedhtmlversion.md#provider-account
      - User Access Management: gettingstartedhtmlversion.md#user-access-management
plugins:
  - techdocs-core
