site_name: 'HCSM User Manual'
nav:
  - Home: gettingstartedhtmlversion.md
  - Overview: gettingstartedhtmlversion.md
  - Purpose: gettingstartedhtmlversion.md
  - Target audience: gettingstartedhtmlversion.md
  - Scope of the solution: gettingstartedhtmlversion.md
  - System requirements: gettingstartedhtmlversion.md
  - Getting Started: gettingstartedhtmlversion.md
  - Features Overview: gettingstartedhtmlversion.md
  - Scope of the solution: gettingstartedhtmlversion.md

plugins:
  - techdocs-core
